### ISSUE TITLE
Error after building the schema

### ISSUE THREAD

**Issue by iamshreeram** [mewil/elastic-graphql#21]
Seeing below error after building the schema.
```
2021/12/03 23:00:57 built document type for dlake-kubernet-namespaces in 1.349116ms
2021/12/03 23:00:57 built boolean argument type for dlake-kubernet-namespaces in 597.751µs
2021/12/03 23:00:57 built document aggregation type for dlake-kubernet-namespaces in 573.113µs
2021/12/03 23:00:57 Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "dlake-kubernet-namespaces" does not.
```

Couldn't trace the root cause. Any suggestion?

cc: @mewil

**Comment by mewil** [comment]
This occurred because GraphQL does not support schema names with `-` in the name. Previously we only applied name normalization logic field and argument names, but as of [e714f3fd](https://github.com/mewil/sturgeon/commit/e714f3fd93f4955e7c911112fb723c42535cef2a) this also applies to index names and should fix your use case.

**Comment by iamshreeram** [comment]
Perfect. This is working. 

Btw, I have set the index include pattern as - `set -gx STURGEON_ELASTICSEARCH_INDEX_INCLUDE_PATTERN "dlake_*"`
But, application is exiting with below exception - 
```
2021/12/09 00:40:59 RootQuery fields must be an object with field names as keys or a function which return such an object.
```
When I use just `dlake*`, sturgeon is able to pull all the index details. Any reason?

**Comment by mewil** [comment]
Great!

This occurs because the `STURGEON_ELASTICSEARCH_INDEX_INCLUDE_PATTERN` variable applies to the literal index name (`dlake-kubernet-namespaces`) and not the "normalized" GraphQL-compatible version (`dlake_kubernet_namespaces`). I'll add better handling for the case where no schemas are generated which yields the error you see.

**Comment by iamshreeram** [comment]
I think you will have to handle all special characters. Below one is failing because of a `.` between dates. 
```
2021/12/09 13:58:09 Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "dlake_pb_batchjobs_2020.05.24_000001_agg_docs" does not.
```

**Comment by mewil** [comment]
Fixed in [d7363dd](https://github.com/mewil/sturgeon/commit/d7363dd53bedd0fde4d5490a63fae457c7b2e4ae) to replace any non-alphanumeric character with `_`.

**Comment by iamshreeram** [comment]
Yes, Above PR fixed the issue. Seeing below error though. 
```
2021/12/11 11:49:25 dlake_snw_inc_bool_argsfilter fields must be an object with field names as keys or a function which return such an object.
exit status 1
```
This looks similar to [this error](https://stackoverflow.com/questions/39401739/graphql-error-fields-must-be-an-object-with-field-names-as-keys-or-a-function-w)

**Comment by mewil** [comment]
This might be fixed in [2ca30dc](https://github.com/mewil/sturgeon/commit/2ca30dc8b5d1be38a4aaaf4211d418f2700c23c9) but similar errors may still occur in other places.

**Comment by iamshreeram** [comment]
Thanks for looking into this. I'm still seeing the same error (in the boolean). Is there any work around for this issue? 

Could you please explain whats going on? If there is any work around just for my use-case, i can fork and make it work just for my ES. Let me know.
